[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["cd backend && mvn install -DskipTests"]

[phases.build]
cmds = ["cd backend && mvn package -DskipTests"]

[start]
cmd = "java -jar backend/target/*.jar"
