spring.application.name=BidStream

# Server port
server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=bidstream
# Using Flyway for schema migrations, so turning off hibernate ddl-auto
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.schemas=bidstream
spring.flyway.create-schemas=true
# Flyway will manage migrations in src/main/resources/db/migration

# Redis Configuration
spring.data.redis.host=${REDISHOST}
spring.data.redis.port=${REDISPORT}
spring.data.redis.password=${REDISPASSWORD}
# If your Redis Cloud requires SSL, set this to true
spring.data.redis.ssl.enabled=true

# JWT Security Property
jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
